// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // El CLI (migraciones, db push, studio) usa la conexión directa a Postgres.
  // El cliente en runtime (lib/prisma/client.ts) usa DATABASE_URL (pooled) por separado.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
